# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97f4b2f2021173096a34a6a588e36653806d94f44b51410e4dcf47c9124ee8d22ea8796ae26e48b0fef16ae7fdfb8b79f834c6e55869b304d9831e187ec247e3

test:
  secret_key_base: d0ca1bb025277371693f67a78218bf5c115355e49589af84d1d6b090a5a7cb6ebf223c195ce9c74e3aa9f7630bb532cf191971e86bc1569bad5454910f5830fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
